version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://localhost:9200

volumes:
  esdata:
    driver: local
