version: "3.4"
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ports:
      - 9200
      - 9300
    network_mode: host
  kibana:
    image: kibana:7.4.2
    ports:
      - 5601
    network_mode: host
    environment:
      ELASTICSEARCH_HOSTS: http://127.0.0.1:9200
